/**
 * Shared branche (sector) list used across signup, campaign wizard, and any
 * other surface that asks the retailer to pick their sector. Keeping a single
 * source ensures the signup default always matches the wizard options.
 */

export const BRANCHE_OPTIES: string[] = [
  'Kapper / Barbershop',
  'Nagelstudio',
  'Schoonheidsspecialist',
  'Tattoo & Piercing',
  'Restaurant',
  'Café / Bar',
  'Koffietentje',
  'Bakkerij',
  'Slagerij',
  'Traiteur / Catering',
  'Afhaal & Bezorging',
  'Pizzeria',
  'Aziatisch restaurant',
  'IJssalon',
  'Sportschool / Fitness',
  'Yoga & Pilates studio',
  'Fysiotherapeut',
  'Personal trainer',
  'Dansschool',
  'Zwembad & Wellness',
  'Meubelwinkel',
  'Keukenwinkel',
  'Interieurwinkel / Woonwinkel',
  'Verfwinkel / Behangwinkel',
  'Doe-het-zelf & Bouwmarkt',
  'Bloemist',
  'Cadeauwinkel',
  'Boekenwinkel',
  'Speelgoedwinkel',
  'Kinderkleding',
  'Boetiek / Kledingwinkel',
  'Schoenenwinkel',
  'Juwelier',
  'Opticien',
  'Drogist',
  'Huisdierenwinkel',
  'Rijschool',
  'Stucadoor / Afbouwbedrijf',
  'Stomerij / Wasserette',
  'Fietsenwinkel',
  'Installatiebedrijf',
  'Schildersbedrijf',
  'Makelaar',
  'Tandarts / Huisarts',
  'Apotheek',
  'Dierenarts',
  'Kinderopvang',
  'Tuincentrum',
  'Overig (neem contact op)',
];
